### ISSUE TITLE
Compiling with Windows

### ISSUE THREAD

**Issue by rbbb** [HiFi-LoFi/KlangFalter#8]
The project is out of sync with Juce (obviously). Managed to compile on Windows by:
replacing AudioBuffer::getSamples by either getReadPointer or getWritePointer
making the custom look and feel subclass LookAndFeel_V1 instead of LookAndFeel

Managed to make the plugin crash by turning it on and off randomly during playback, meaning that CopyAndPad in Utilities.h had too small a buffer and gave an assertion failure.

Impulses: http://fokkie.home.xs4all.nl/IR.htm

Here's a windows compile to VST, run through a couple of antivirus and rename to DLL.

Good stuff

![klangfalter dll](https://cloud.githubusercontent.com/assets/5883308/11238924/3a5e7fac-8de9-11e5-8609-50dfdb7fb39a.png)

**Comment by HiFi-LoFi** [comment]
Hi rbbb,

sorry for not answering earlier, I was more in making music than in making music software the recent time... ;-)

I've just updated the KlangFalter code to Juce 4.2.3, so your compiling issues should be solved now.

As I'm only using Mac at the moment, I'm afraid I can't really help with your Windows build because I can't debug it here.

Regards, Uli
